services:
  postgres:
    image: postgres:16-alpine
    container_name: urlshortener-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: urlshortener
    ports:
      - "5434:5432"
    volumes:
      - urlshortener_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - urlshortener-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d urlshortener" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlshortener-app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urlshortener
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - urlshortener-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  urlshortener_postgres_data:


networks:
  urlshortener-network:
    driver: bridge
